<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Anita" failures="1" tests="1" name="Checkbox Demo" time="13.81" errors="0" timestamp="2020-11-30T09:26:03 CET">
  <testcase classname="sEasyDemo.SE.CheckBoxDemoTest" name="clickCheckboxes" time="3.421">
    <failure type="java.lang.AssertionError" message="expected [Success - Check box is checkedl] but found [Success - Check box is checked]">
      <![CDATA[java.lang.AssertionError: expected [Success - Check box is checkedl] but found [Success - Check box is checked]
at sEasyDemo.SE.CheckBoxDemoTest.clickCheckboxes(CheckBoxDemoTest.java:54)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- clickCheckboxes -->
</testsuite> <!-- Checkbox Demo -->
